[package]
name = "kanjisabi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "*"
hotkey = "*"
jni = "*"
tokio = { version = "1", features = ["full"] }
wgpu = "*"
winit = "*"
