[package]
name = "kanjisabi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
device_query = "*"
fontconfig = { git = "https://github.com/makemeunsee/fontconfig-rs" }
jmdict = "*"
kanji = { git = "https://github.com/makemeunsee/rs-kanji" }
screenshot = { git = "https://github.com/makemeunsee/screenshot-rs" }
tauri-hotkey = "*"
tesseract = "*"
tesseract-sys = "*"

[dev-dependencies]
qt_widgets = "*"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["ttf"]
