[package]
name = "kanjisabi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "*"
tauri-hotkey = "*"
tesseract-sys = "*"
screenshot = { git = "https://github.com/makemeunsee/screenshot-rs" }
# screenshot = { path = "../screenshot-rs" }
# tesseract = "*"
tesseract = { git = "https://github.com/makemeunsee/tesseract-rs" }
# tesseract = { path = "../tesseract-rs" }

jni = "*"
tokio = { version = "1", features = ["full"] }
wgpu = "*"
winit = "*"
egui-winit = "*"
