[package]
name = "kanjisabi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
device_query = "*"
fontconfig = "0.5.0"
jmdict = "*"
libc = "*"
screenshot = { git = "https://github.com/makemeunsee/screenshot-rs" }
sdl2-sys = "*"
tauri-hotkey = "*"
tesseract = "*"
tesseract-sys = "*"

[dev-dependencies]
qt_widgets = "*"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["ttf"]

[dependencies.x11rb]
version = "*"
default-features = false
features = ["xfixes"]
